### ISSUE TITLE
Word error rate is high when using any of the models

### ISSUE THREAD

**Issue by spacether** [microsoft/Cognitive-Custom-Speech-Service#2]
Running accuracy tests on your data here: https://cris.ai/AccuracyTests
with the below models on the Sample1 - Biology/Test Data/Test Acoustic Data/ data set yielded:

Acoustic Model/Language Model      Word Error Rate (%)
Microsoft Conversational Model/same         39.87
bio_data_model/Microsoft Conversational Model                                        33.04
Microsoft Search and Dictation Model/same   43.61

Note: the above tests did not use a custom language model

**Comment by hsoncu** [comment]
Hi @spacether,

This is Hakan from Cognitive Custom Speech Service Team.

You are right that the word error rate is very low when you only create your custom "Acoustic Model" without "Language Model". Actually, it is expected. If you look at the transcriptions of the sample data, you will see many  latin words which are specific to the domain and these words are not defined in the base model. 

In order to have these domain specific words in your model, you need to first adapt a language model. Then the system can be aware of them. Without a language model adaptation, acoustic model may understand the vocal but cannot map it to the correct word. This is what happened in your tests. 

I have run also the same test and here are the results:

Only AM Adaptation: 33.04 % WER
Only LM Adaptation : 10.13 % WER
Both LM and AM Adaptation: 2.86% WER

Thanks,

Hakan

**Comment by spacether** [comment]
@hsoncu thanks for the quick response!

Key take-aways:
- The custom language model decreases the word error rate from ~30 or 40% to 10%
- The custom language model + custom acoustic model further reduces the error rate to 3%
